# Generated by Django 6.0.1 on 2026-01-23 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cohort 1, Cohort 2', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g., C1, C2', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active cohorts appear in registration')),
                ('is_new_intake', models.BooleanField(default=False, help_text='Is this a new intake cohort?')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Single letter code: A, S, P, I, R', max_length=1, unique=True)),
                ('name', models.CharField(help_text='Full name of the dimension', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active dimensions appear in registration')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which dimensions appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensions',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('NEW', 'New Learner'), ('RETURNING', 'Returning Learner')], max_length=10, unique=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, help_text='Registration fee amount', max_digits=10)),
                ('course_fee', models.DecimalField(decimal_places=2, help_text='Course fee amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ASPIR Mentorship Program', max_length=200)),
                ('site_tagline', models.CharField(default='A step-by-step journey to Purpose, Excellence & Leadership', max_length=300)),
                ('group1_min_age', models.IntegerField(default=10, help_text='Minimum age for Group 1')),
                ('group1_max_age', models.IntegerField(default=15, help_text='Maximum age for Group 1')),
                ('group2_min_age', models.IntegerField(default=16, help_text='Minimum age for Group 2')),
                ('group2_max_age', models.IntegerField(default=22, help_text='Maximum age for Group 2')),
                ('guardian_required_age', models.IntegerField(default=16, help_text='Age below which guardian info is required')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Settings',
                'verbose_name_plural': 'Program Settings',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(22)])),
                ('group', models.CharField(choices=[('G1', 'Group 1 (10-15 years)'), ('G2', 'Group 2 (16-22 years)')], max_length=2)),
                ('enrollment_type', models.CharField(choices=[('NEW', 'New Learner'), ('RETURNING', 'Returning Learner')], max_length=10)),
                ('cohort_code', models.CharField(blank=True, max_length=2, null=True)),
                ('dimension_code', models.CharField(blank=True, max_length=1, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about us?', max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=10)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.cohort')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.dimension')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Raw Paystack webhook payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
