# Generated by Django 6.0.1 on 2026-01-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='squad_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
