# Generated by Django 6.0.1 on 2026-01-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_squad_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course fee amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether course fee has been paid'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Registration fee amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether registration fee has been paid'),
        ),
    ]
