# Generated by Django 6.0.1 on 2026-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_partial_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('NGN', 'NGN - Nigerian Naira')], default='USD', help_text='Currency for this pricing configuration', max_length=3),
        ),
    ]
